### PR TITLE
Clarify read-csv

### LINKED ISSUE #17: Trailing new lines add additional fields
Here's the `cljs.test` output from a failing test I wrote. I discovered this while fixing https://github.com/testdouble/clojurescript.csv/issues/13, but I believe they can be addressed separately.
```
expected: (= [["a" "b" "c"]] (csv/read-csv "a,b,c\n"))
  actual: (not (= [["a" "b" "c"]] [["a" "b" "c" ""]]))
```

### PR DESCRIPTION
**Pull request by mainej**
This includes several clarifications to the csv parser.
* end-of-field and end-of-line handling is inlined, meaning there doesn't need to be a separate variable that tracks those states. The `loop` is a state machine itself, so having a separate state machine was extraneous.
* Quoted fields are parsed separately, so the logic for those fields is no longer interspersed among the other logic.
* Repeated tasks have been extracted into helper functions.

Together these changes result in shorter code that passes the existing tests. It also results, to my eye, in clearer code that is easier to debug.

With the easier debugging, I found and fixed several bugs. They are outlined in the new tests, including bugs around the handling of headers, quotes, separators (especially at the beginning and end of a line) and line endings, (especially at the beginning and end of a file). 

This fixes the bug described in #22. If this PR is merged, that one can be closed.

It also fixes #17. However, that Issue suggests that `a,b,c\n` should be read as `[["a" "b" "c"]]`. I contend differently. In my opinion, a trailing newline should not be ignored. Instead, it should indicate a new row. 

It also seems odd to me that a row with 1 comma would have 2 fields, but a row with 0 commas would have 0 fields. Instead, I think that a row with 0 commas should have 1 field; if it is a blank row that single field should be an empty string.

Taken together that means `a,b,c\n` should be read as `[["a" "b" "c"] [""]]`.

The new code reflects my opinions but we are deep into the world of CSV ambiguities. I think my interpretations are reasoned, but I can't claim they're "right". I like the simplicity of this implementation, and like that it fixes many bugs, but will understand if it's too big of a change.

### CODE REVIEW

**Review by rosston — APPROVED** [review]
First of all, thank you for your patience as I've taken months to look at this in depth.

Second of all, these changes looks great! You've knocked 50 lines of code off and made the function much easier to understand than what I had previously.

>Taken together that means `a,b,c\n` should be read as `[["a" "b" "c"] [""]]`.

Your reasoning makes sense. Truthfully, I don't like the conclusion. 🙂 But between your reasoning, the way that that reasoning makes the code simpler (no special case for trailing new line), and the fact that this result is better than the current behavior; I'm happy to overlook my displeasure with the conclusion.

I'll work on getting this merged and deployed today. Thanks again!

**Comment by rosston** [comment]
Released in v0.5.0.

**Comment by mainej** [comment]
Thanks for merging. I agree, the conclusions may be a bit contrived to conveniently support the code. And though I can imagine adding special handling for trailing newlines, I'm glad to avoid that additional complexity. I hope that with the new tests users will at least be able to see how this code processes blank fields and trailing newlines, and adapt their code to handle their messy CSVs. :)

In looking over this PR once more, I see another un-handled edge case: lone newlines within a cr-lf file. It's so hard to get all the logic right! I'll submit another PR with that test case and a fix.

**Comment by rosston** [comment]
I very much appreciate the amount of additional testing and edge cases you covered!

And yeah, parsing CSVs is a whole bunch of un-handled edge cases, mostly ones that don't have clearly defined or preferred behavior. 😬

**Pull request merged**
