### PR TITLE
support non string values in quoted csv

### PR DESCRIPTION
**Pull request by ephigabay**

### CODE REVIEW

**Comment by rosston** [comment]
Let me think on this for a little bit. I _think_ what you've done here is the right thing (because you could argue converting to string is part of the job of the CSV serialization), but there's a part of me that wonders if that should be separate from the serialization that's happening here.

**Comment by ephigabay** [comment]
@rosston Yes, I see no reason not to support non string values as the current state throws an exception when serializing non string values and adding quotes. This is the best place I found to add this piece of code. If you think somewhere else is better feel free to change the code :)

**Comment by rosston** [comment]
Alright, I see now that non-string values are already being `str`ed when `quote? false`. I'm good with this approach then.

Would you mind adding tests for:
1) `str`ing of values even when `quote? false` (to make this behavior explicit)
2) `str`ing of `nil` (since it was raised in https://github.com/testdouble/clojurescript.csv/issues/18; this can just go in the `str`-related tests)

**Comment by rosston** [comment]
Merging as is. I can make the changes I requested on `master`. Thanks for the contribution!

**Pull request merged**
